### ISSUE TITLE
Setup actions workflow

### ISSUE THREAD

**Issue by asimbera** [BlueBlaze6335/Illicit-Illustrations#13]
Setup GitHub actions workflow to automatically test the code on every pull request and make a release on every tag.
In this way, it will be easier to find potential bugs before the code review.

Tasks:
- [x] Set up a workflow to run unit and integration tests on PR.
- [x] Set up a workflow to distribute apk/ipa 's on each tag.

**Comment by BlueBlaze6335** [comment]
@asimbera I  have assigned this issue to you !
