### ISSUE TITLE
Add a image editor page to let the user crop and change the saturation/contrast/brightness of image before adding filter.

### ISSUE THREAD

**Issue by ayush-150101** [BlueBlaze6335/Illicit-Illustrations#21]

**Comment by ayush-150101** [comment]
Presently the image cannot be fitted to user needs. To give the user more flexibility add a image editor screen which will be navigated to from the camera screen on tapping edit icon that will let the user make changes to the image.

**Comment by sayanm16** [comment]
want to contribute in this issue.....pls assign it to me.
