### ISSUE TITLE
Create an icon for the app. It should be something related to the name and the theme of the app.

### ISSUE THREAD

**Issue by ayush-150101** [BlueBlaze6335/Illicit-Illustrations#22]

**Comment by JaynouOliver** [comment]
Please assign this work to me! I can do it easily within no time!

**Comment by BlueBlaze6335** [comment]
@JaynouOliver are you a participant in JWOC ?

**Comment by JaynouOliver** [comment]
yes

**Comment by BlueBlaze6335** [comment]
Great !! I am assigning this issue to you !

**Comment by JaynouOliver** [comment]
Thanks! What is the deadline ?

**Comment by JaynouOliver** [comment]
I will try to finish this by today then

**Comment by BlueBlaze6335** [comment]
Please use discord to communicate with us as it becomes hard to answer in comments !!
