### ISSUE TITLE
Toast Message

### ISSUE THREAD

**Issue by ayush-150101** [BlueBlaze6335/Illicit-Illustrations#7]
Implement a toast message indicating the artistic style on each style applied

**Comment by aryanraj2713** [comment]
Implement a toast message indicating the artistic style on each style applied

**Comment by BlueBlaze6335** [comment]
@aryanraj2713 these issues are for JWOC and if you have registered at [jwoc.tech](https://jwoc.tech/) then please abstain from commenting on issues before 1st Feb , otherwise , if you are not registered at JWOC , then please register as a mentee [here](https://jwoc.tech/).

**Comment by sayanm16** [comment]
Want to work on this issue. Pls assign me in this want to contribute in this issue toast message.

**Comment by sayanm16** [comment]
want to work on this issue. pls assign me in this

**Comment by BlueBlaze6335** [comment]
@sayanm16 I have assigned this issue to you , start working on this !! Happy contribution !

**Comment by sayanm16** [comment]
> @sayanm16 I have assigned this issue to you , start working on this !! Happy contribution !

Thanks for the oppourtunity!!!!

**Comment by BlueBlaze6335** [comment]
Great job @sayanm16  !!
