### ISSUE TITLE
Image being rotated in some devices

### ISSUE THREAD

**Issue by ayush-150101** [BlueBlaze6335/Illicit-Illustrations#9]
The image is being rotated in some devices on running it against the tflite model. 

The original image is in correct orientation. But once it is processed using the tflite.pix2pix function, the orientation of the output image is being rotated.

**Comment by Nishikanta059** [comment]
I want to try on this issue

**Comment by sayanm16** [comment]
I got the solution for this issue pls assign it to me.

**Comment by BlueBlaze6335** [comment]
@sayanm16  great !! I am assigning this to you !!

**Comment by BlueBlaze6335** [comment]
Great job done by @sayanm16
